import { Problem } from "./types";

export const problems: Problem[] = [
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 동일한 내용의 데이터가 중복되어 있지 않은 것",
    correctA: "통합된 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 컴퓨터의 저장매체에 있는 것.",
    correctA: "저장된 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 여러 사용자가 서로 다른 목적으로 접근할 수 있는 것",
    correctA: "공용 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 새로운 데이터의 삽입, 기존 데이터의 수정, 삭제, 업데이트를 하여 항상 최신의 정확한 데이터 상태를 유지하는 것",
    correctA: "변화하는 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "학습과 체험을 통해 개인에게 습득되어 있지만 겉으로 드러나지 않는 상태의 지식",
    correctA: "암묵지",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "문서나 매뉴얼처럼 외부로 표출돼 여러 사람이 공유할 수 있는 지식",
    correctA: "형식지",
    category: "1",
    tags: ["1일차"],
  },

  {
    type: "SHORT_ORDER",
    q: "암묵지-형식지의 상호작용: 조직의 지식으로 ___를 위한 ___, 개인에게 ___ 및 습득되는 ___",
    correctA: ["공통화", "표출화", "연결", "내면화"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "객관적인 사실로부터 얻을 수 있는 것들을 차례대로.",
    correctA: ["데이터", "정보", "지식", "지혜"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "데이터베이스의 다섯가지 측면 (측면이라는 말 제외)",
    correctA: [
      "정보의 축적 및 전달",
      "정보이용",
      "정보관리",
      "정보기술발전",
      "경제 산업적",
    ],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터베이스에서 명령을 수행하는 하나의 단위",
    correctA: "트랜잭션",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "트랜잭션 네 가지 특성",
    correctA: ["원자성", "일관성", "고립성", "지속성"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "각각 거래 단위에 초점을 맞추는 데 목적이 있는 시스템 (예: 주문입력)",
    correctA: "OLTP",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "전체 데이터를 분석하기 위한 시스템",
    correctA: "OLAP",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "서비스 간 연계가 필요할 경우 중앙에서 관리를 위한 것",
    correctA: "EAI",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "기업이 보유할 수 있는 모든 지식을 통합 -> 문제 해결 능력 향상하기 위한 것",
    correctA: "KMS",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "공급을 관리하는 시스템",
    correctA: "SCM",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "고객을 관리하는 시스템",
    correctA: "CRM",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "제조 부문에서 자원에 대한 구매/생산을 효율적으로 하기 위한 시스템",
    correctA: "ERP",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "제조 부문에서 기업의 의사결정을 돕는 프로세스",
    correctA: "BI",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터를 설명하는 데이터",
    correctA: "메타데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터를 설명하는 데이터",
    correctA: "메타데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터의 특징을 이야기할 때: __의 __",
    correctA: ["더그 래니", "3V"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "빅데이터 특징 3V (소문자로)",
    correctA: ["volume", "variety", "velocity"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "3V 에 하나로 추가하는 것은 ___ 또는 ___ 이다. (햔국어로)",
    correctA: ["가치", "정확성"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "빅데이터가 만들어내는 변화 네 가지",
    correctA: ["사후처리", "전수조사", "양", "상관관계"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 ____의 석탄, 철! 생산성을 획기적으로 끌어올림.",
    correctA: "산업혁명",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 21세기 ___! 산업 전반의 생산성을 향상시키고 새로운 범주의 산업을 만들어낼 것임!",
    correctA: "원유",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 ___! 생물학에 큰 영향을 끼친 ___ 처럼 산업 발전에 큰 영향을 줄 것이다.",
    correctA: "렌즈",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 ___! (여러 사람이 공동으로 사용 가능한 구조물) 예: 페이스북, 카카오톡",
    correctA: "플랫폼",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "___ 이란 헤겔의 변증법에 기초를 둔 개념으로, 양적인 변화가 축적되면 질적인 변화도 이루어진다는 개념이다.",
    correctA: "양질 전환의 법칙",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "___ 이란 헤겔의 변증법에 기초를 둔 개념으로, 양적인 변화가 축적되면 질적인 변화도 이루어진다는 개념이다.",
    correctA: "양질 전환의 법칙",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "빅데이터 가치 산정 어려움의 이유 - ___의 다양화 세 가지",
    correctA: ["가치 창출 방식", "데이터 활용 방식", "분석 기술의 발전"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "미래의 빅데이터 활용에 필요한 3요소",
    correctA: ["데이터", "기술", "인력"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "7가지 데이터 활용 기본 테크닉",
    correctA: [
      "연관규칙 학습",
      "유형분석",
      "유전 알고리즘",
      "기계학습",
      "회귀분석",
      "감정분석",
      "소셜 네트워크 분석",
    ],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중 어떤 변인 간에 주목할 만한 상관 관계가 있는지를 찾아내는 방법",
    correctA: "연관규칙 학습",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중 새로운 사건이 속할 범주를 찾아내는 방법",
    correctA: "유형분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중 최적화가 필요한 문제의 해결책을 자연선택, 돌연변이 등과 같은 메커니즘을 통해 점진적으로 진화시켜 나가는 방법",
    correctA: "유전 알고리즘",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 컴퓨터가 데이터로부터 규칙을 찾고 이러한 규칙을 활용해 '예측'하는 데 초점을 둔 방법",
    correctA: "기계학습",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 독립변수를 조작하면서 종속변수가 어떻게 변하는지를 보며 수치형으로 이루어진 두 변인의 관계를 파악하는 방법",
    correctA: "회귀분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 특정 주제에 대해 말하거나 글을 쓴 사람의 감정을 분석하는 방법",
    correctA: "감정분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 온라인 공간에서 영향력 있는 사람을 찾아내어 기업의 효율적인 마케팅이나 범죄 수사에서 공범을 찾는 등 다양한 분야에서 활용될 수 있음.",
    correctA: "소셜 네트워크 분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "위기 요인 세 가지",
    correctA: ["사생활 침해", "책임 원칙 훼손", "데이터 오용"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "조지 오웰의 <1984>, SNS에 여행 게시글을 올린 사용자를 대상으로 한 빈집털이 발생과 관련된 빅데이터 위기요인은?",
    correctA: "사생활 침해",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "영화 <마이너리티 리포트>, 신용카드 발급 여부 판단에 있어 불이익 발생 등과 관련된 빅데이터 위기요인은?",
    correctA: "책임 원칙 훼손",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "포드의 자동차 발명, 스티브 잡스의 아이폰 발명 (이전에는 없었던 창조적인 물건에 대한 미래는 예측하기 힘듬) 등과 관련된 빅데이터 위기요인은?",
    correctA: "데이터 오용",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "사생활 침해의 통제 방안은 동의에서 ___으로",
    correctA: "책임",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "책임 원칙 훼손의 통제 방안은 ___ 책임 원칙 고수.",
    correctA: "결과 기반",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "데이터가 오용되었을 때에는, 데이터가 어떻게 사용되어 어떠한 이유로 피해자가 발생하게 되었는지 ___ 를 살펴봄으로써 피해자를 구제할 수 있다.",
    correctA: "알고리즘",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "___ 이란, 데이터 속에서 개인을 식별할 수 있는 요인을 숨김으로써 개인을 특정할 수 없도록 하는 기술이다.",
    correctA: "개인정보 비식별 기술",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "데이터 사이언스 구성 요소 세 가지",
    correctA: ["Analytics", "IT", "비즈니스 분석"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "다른 이해 관계자들이 보완적인 상품, 서비스를 제공하는 생태계를 구축하고자 하는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "플랫폼형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "기업이 부가가치를 생산하는 과정을 통합/세분화하여 시장 상황에 빠르게 대응할 수 있는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "가치사슬형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "거래 사이트가 직접 거래하지 않고 공급자와 수요자들이 자유롭게 거래할 수 있도록 하는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "대리인형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "다양한 공급자와 수요자들이 만나는 사이트르 운영하는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "상거래형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임의 첫번째",
    correctA: "디지털화",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임의 두번째",
    correctA: "연결",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임의 세번째",
    correctA: "에이전시",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임 중 운영체제, 워드/파워포인트 같은 오피스 프로그램과 같은 것",
    correctA: "디지털화",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임 중 구글의 검색 알고리즘, 네이버의 콘텐츠 등과 관련된 것",
    correctA: "연결",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임 중 복잡한 연결을 얼마나 효과적으로 관리하는 가의 이슈",
    correctA: "에이전시",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "PICK_DIFFERENT",
    q: "데이터 사이언스 구성 요소",
    pool: [
      [
        "수학",
        "확률 모델",
        "머신러닝",
        "분석학",
        "패턴 인식과 학습",
        "불확실성 모델링",
      ],
      [
        "시그널 프로세싱",
        "프로그래밍",
        "데이터 엔지니어링",
        "데이터 웨어하우징",
        "고성능 컴퓨팅",
      ],
      ["커뮤니케이션", "프레젠테이션", "스토리텔링", "시각화"],
    ],
    category: "1",
    tags: ["2일차"],
    weight: 2,
  },
  {
    type: "SHORT_MULTI",
    q: "소프트 스킬 세 가지",
    correctA: ["통찰력 있는 분석", "설득력 있는 전달", "다분야 간 협력"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "하드 스킬 두 가지: ___에 대한 이론적 지식, ___에 대한 숙련",
    correctA: ["빅데이터", "분석 기술"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "가트너가 제시한 데이터 사이언티스트 역량 네 가지",
    correctA: ["데이터 관리", "분석 모델링", "비즈니스 분석", "소프트 스킬"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "외부 환경에서 본 인문학의 열풍: ",
    correctA: ["통찰력 있는 분석", "설득력 있는 전달", "다분야 간 협력"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "추론, 예측, 전망, 추정을 위한 정보의 근거가 될 수 있는 데이터의 특성을 데이터의 ___라고 한다.",
    correctA: "데이터의 당위적 특성",
    tags: ["핵심 서브노트 110제"],
  },
  {
    type: "SHORT",
    q: "고정된 틀이 존재하지 않고 연산이 불간으하며, 수집과 관리가 어려워 일반적으로 관계형 DB가 아닌 NoSQL DB에 저장되는 데이터는 무엇인가?",
    correctA: "비정형 데이터",
    tags: ["핵심 서브노트 110제"],
  },
  {
    type: "SHORT",
    q: "학습과 체험을 통해 개인에게 습득되어 있지만 겉으로 드러나지 않는 상태의 지식. 문자나 언어로 나타나지 않음.",
    correctA: "암묵지",
    tags: ["핵심 서브노트 110제"],
  },
  {
    type: "SHORT_ORDER",
    q: "개인에게 내면화된 암묵지가 조직의 지식으로 ___되기 위해서는, 표출화하고 이를 다시 개인의 지식으로 ___ 하는 과정을 거치게 된다.",
    correctA: ["공통화", "연결화"],
    tags: ["핵심 서브노트 110제"],
  },
  {
    type: "SHORT",
    q: "",
    correctA: "",
    tags: ["핵심 서브노트 110제"],
  },
];
