import { Problem } from "./types";

export const problems: Problem[] = [
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 동일한 내용의 데이터가 중복되어 있지 않은 것",
    correctA: "통합된 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 컴퓨터의 저장매체에 있는 것.",
    correctA: "저장된 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 여러 사용자가 서로 다른 목적으로 접근할 수 있는 것",
    correctA: "공용 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터의 일반적인 특징 중 새로운 데이터의 삽입, 기존 데이터의 수정, 삭제, 업데이트를 하여 항상 최신의 정확한 데이터 상태를 유지하는 것",
    correctA: "변화하는 데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "학습과 체험을 통해 개인에게 습득되어 있지만 겉으로 드러나지 않는 상태의 지식",
    correctA: "암묵지",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "문서나 매뉴얼처럼 외부로 표출돼 여러 사람이 공유할 수 있는 지식",
    correctA: "형식지",
    category: "1",
    tags: ["1일차"],
  },

  {
    type: "SHORT_ORDER",
    q: "암묵지-형식지의 상호작용: 조직의 지식으로 ___를 위한 ___, 개인에게 ___ 및 습득되는 ___",
    correctA: ["공통화", "표출화", "연결", "내면화"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "객관적인 사실로부터 얻을 수 있는 것들을 차례대로.",
    correctA: ["데이터", "정보", "지식", "지혜"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "데이터베이스의 다섯가지 측면 (측면이라는 말 제외)",
    correctA: [
      "정보의 축적 및 전달",
      "정보이용",
      "정보관리",
      "정보기술발전",
      "경제 산업적",
    ],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "DB의 ___ 측면: 이용자의 정보 요구에 따라 원하는 정보를 신속하고 정확하고 경제적으로 찾아내거나 획득 가능",
    correctA: "정보이용",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "DB의 ___ 측면: 정리, 저장, 검색, 관리, 체계적으로 축적, 추가나 갱신 용이한 측면",
    correctA: "정보관리",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "DB의 ___ 측면: 네트워크 기술의 발달을 견인할 수 있음.",
    correctA: "정보기술발전",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "DB의 ___ 측면: 국민의 편의를 증진하고 사회 활동의 효율성 제고",
    correctA: "경제산업적",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터베이스에서 명령을 수행하는 하나의 단위",
    correctA: "트랜잭션",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "트랜잭션 네 가지 특성",
    correctA: ["원자성", "일관성", "고립성", "지속성"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "영역별로 구축되던 단순 자동화 중심, 각각 거래 단위에 초점을 맞추는 데 목적이 있음 (예: 주문입력)",
    correctA: "OLTP",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터마이닝 등의 기술이 등장하며, 단순한 정보의 수집과 공유에서 탈피하여 분석이 중심이 되는 것",
    correctA: "OLAP",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "기업에서 서비스 간 연계가 필요할 경우, 기하급수적으로 증가하는 연결 루트를 간소화하기 위해 중앙에서 관리하는 것",
    correctA: "EAI",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "기업이 보유할 수 있는 모든 지식을 통합 -> 문제 해결 능력 향상하기 위한 것",
    correctA: "KMS",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "공급을 관리하는 시스템",
    correctA: "SCM",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "고객을 관리하는 시스템",
    correctA: "CRM",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "제조 부문에서 자원에 대한 구매/생산을 효율적으로 하기 위한 시스템",
    correctA: "ERP",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "제조 부문에서 기업의 의사결정을 돕는 프로세스",
    correctA: "BI",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터를 설명하는 데이터",
    correctA: "메타데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "데이터를 설명하는 데이터",
    correctA: "메타데이터",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터의 특징을 이야기할 때: __의 __",
    correctA: ["더그 래니", "3V"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "빅데이터 특징 3V (소문자로)",
    correctA: ["volume", "variety", "velocity"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "3V 에 하나로 추가하는 것은 ___ 또는 ___ 이다. (햔국어로)",
    correctA: ["가치", "정확성"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "빅데이터가 만들어내는 변화 네 가지",
    correctA: ["사후처리", "전수조사", "양", "상관관계"],
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 ____의 석탄, 철! 생산성을 획기적으로 끌어올림.",
    correctA: "산업혁명",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 21세기 ___! 산업 전반의 생산성을 향상시키고 새로운 범주의 산업을 만들어낼 것임!",
    correctA: "원유",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 ___! 생물학에 큰 영향을 끼친 ___ 처럼 산업 발전에 큰 영향을 줄 것이다.",
    correctA: "렌즈",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터의 역할: 빅데이터는 ___! (여러 사람이 공동으로 사용 가능한 구조물) 예: 페이스북, 카카오톡",
    correctA: "플랫폼",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "___ 이란 헤겔의 변증법에 기초를 둔 개념으로, 양적인 변화가 축적되면 질적인 변화도 이루어진다는 개념이다.",
    correctA: "양질 전환의 법칙",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT",
    q: "___ 이란 헤겔의 변증법에 기초를 둔 개념으로, 양적인 변화가 축적되면 질적인 변화도 이루어진다는 개념이다.",
    correctA: "양질 전환의 법칙",
    category: "1",
    tags: ["1일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "빅데이터 가치 산정 어려움의 이유 - ___의 다양화 세 가지",
    correctA: ["가치 창출 방식", "데이터 활용 방식", "분석 기술의 발전"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "미래의 빅데이터 활용에 필요한 3요소",
    correctA: ["데이터", "기술", "인력"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "7가지 데이터 활용 기본 테크닉",
    correctA: [
      "연관규칙 학습",
      "유형분석",
      "유전 알고리즘",
      "기계학습",
      "회귀분석",
      "감정분석",
      "소셜 네트워크 분석",
    ],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중 어떤 변인 간에 주목할 만한 상관 관계가 있는지를 찾아내는 방법",
    correctA: "연관규칙 학습",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중 새로운 사건이 속할 범주를 찾아내는 방법",
    correctA: "유형분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중 최적화가 필요한 문제의 해결책을 자연선택, 돌연변이 등과 같은 메커니즘을 통해 점진적으로 진화시켜 나가는 방법",
    correctA: "유전 알고리즘",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 컴퓨터가 데이터로부터 규칙을 찾고 이러한 규칙을 활용해 '예측'하는 데 초점을 둔 방법",
    correctA: "기계학습",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 독립변수를 조작하면서 종속변수가 어떻게 변하는지를 보며 수치형으로 이루어진 두 변인의 관계를 파악하는 방법",
    correctA: "회귀분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 특정 주제에 대해 말하거나 글을 쓴 사람의 감정을 분석하는 방법",
    correctA: "감정분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "7가지 데이터 활용 기본 테크닉 중, 온라인 공간에서 영향력 있는 사람을 찾아내어 기업의 효율적인 마케팅이나 범죄 수사에서 공범을 찾는 등 다양한 분야에서 활용될 수 있음.",
    correctA: "소셜 네트워크 분석",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "위기 요인 세 가지",
    correctA: ["사생활 침해", "책임 원칙 훼손", "데이터 오용"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "조지 오웰의 <1984>, SNS에 여행 게시글을 올린 사용자를 대상으로 한 빈집털이 발생과 관련된 빅데이터 위기요인은?",
    correctA: "사생활 침해",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "영화 <마이너리티 리포트>, 신용카드 발급 여부 판단에 있어 불이익 발생 등과 관련된 빅데이터 위기요인은?",
    correctA: "책임 원칙 훼손",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "포드의 자동차 발명, 스티브 잡스의 아이폰 발명 (이전에는 없었던 창조적인 물건에 대한 미래는 예측하기 힘듬) 등과 관련된 빅데이터 위기요인은?",
    correctA: "데이터 오용",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "사생활 침해의 통제 방안은 동의에서 ___으로",
    correctA: "책임",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "책임 원칙 훼손의 통제 방안은 ___ 책임 원칙 고수.",
    correctA: "결과 기반",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "데이터가 오용되었을 때에는, 데이터가 어떻게 사용되어 어떠한 이유로 피해자가 발생하게 되었는지 ___ 를 살펴봄으로써 피해자를 구제할 수 있다.",
    correctA: "알고리즘",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "___ 이란, 데이터 속에서 개인을 식별할 수 있는 요인을 숨김으로써 개인을 특정할 수 없도록 하는 기술이다.",
    correctA: "개인정보 비식별 기술",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "데이터 사이언스 구성 요소 세 가지",
    correctA: ["Analytics", "IT", "비즈니스 분석"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "다른 이해 관계자들이 보완적인 상품, 서비스를 제공하는 생태계를 구축하고자 하는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "플랫폼형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "기업이 부가가치를 생산하는 과정을 통합/세분화하여 시장 상황에 빠르게 대응할 수 있는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "가치사슬형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "거래 사이트가 직접 거래하지 않고 공급자와 수요자들이 자유롭게 거래할 수 있도록 하는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "대리인형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "다양한 공급자와 수요자들이 만나는 사이트르 운영하는 비즈니스 모델은 ___ 비즈니스 모델이다.",
    correctA: "상거래형",
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임의 첫번째",
    correctA: "디지털화",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임의 두번째",
    correctA: "연결",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임의 세번째",
    correctA: "에이전시",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임 중 운영체제, 워드/파워포인트 같은 오피스 프로그램과 같은 것",
    correctA: "디지털화",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임 중 구글의 검색 알고리즘, 네이버의 콘텐츠 등과 관련된 것",
    correctA: "연결",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "SHORT",
    q: "빅데이터 가치 패러다임 중 복잡한 연결을 얼마나 효과적으로 관리하는 가의 이슈",
    correctA: "에이전시",
    category: "1",
    tags: ["2일차"],
    weight: 0.6,
  },
  {
    type: "PICK_DIFFERENT",
    q: "데이터 사이언스 구성 요소",
    pool: [
      [
        "수학",
        "확률 모델",
        "머신러닝",
        "분석학",
        "패턴 인식과 학습",
        "불확실성 모델링",
      ],
      [
        "시그널 프로세싱",
        "프로그래밍",
        "데이터 엔지니어링",
        "데이터 웨어하우징",
        "고성능 컴퓨팅",
      ],
      ["커뮤니케이션", "프레젠테이션", "스토리텔링", "시각화"],
    ],
    category: "1",
    tags: ["2일차"],
    weight: 2,
  },
  // {
  //   type: "SHORT_MULTI",
  //   q: "소프트 스킬 일곱 가지",
  //   correctA: ["통찰력 있는 분석", "설득력 있는 전달", "다분야 간 협력"],
  //   category: "1",
  //   tags: ["2일차"],
  // },
  {
    type: "SHORT_MULTI",
    q: "소프트 스킬 일곱 가지",
    correctA: [
      "창의적 사고",
      "호기심",
      "논리적 비판",
      "창의력",
      "스토리텔링",
      "시각화",
      "커뮤니케이션",
    ],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "하드 스킬 두 가지: ___에 대한 이론적 지식, ___에 대한 숙련",
    correctA: ["빅데이터", "분석 기술"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_MULTI",
    q: "가트너가 제시한 데이터 사이언티스트 역량 네 가지",
    correctA: ["데이터 관리", "분석 모델링", "비즈니스 분석", "소프트 스킬"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT_ORDER",
    q: "외부 환경에서 본 인문학의 열풍: ",
    correctA: ["통찰력 있는 분석", "설득력 있는 전달", "다분야 간 협력"],
    category: "1",
    tags: ["2일차"],
  },
  {
    type: "SHORT",
    q: "추론, 예측, 전망, 추정을 위한 정보의 근거가 될 수 있는 데이터의 특성을 데이터의 ___라고 한다.",
    correctA: "데이터의 당위적 특성",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "고정된 틀이 존재하지 않고 연산이 불간으하며, 수집과 관리가 어려워 일반적으로 관계형 DB가 아닌 NoSQL DB에 저장되는 데이터는 무엇인가?",
    correctA: "비정형 데이터",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "학습과 체험을 통해 개인에게 습득되어 있지만 겉으로 드러나지 않는 상태의 지식. 문자나 언어로 나타나지 않음.",
    correctA: "암묵지",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT_ORDER",
    q: "개인에게 내면화된 암묵지가 조직의 지식으로 ___되기 위해서는, 표출화하고 이를 다시 개인의 지식으로 ___ 하는 과정을 거치게 된다.",
    correctA: ["공통화", "연결화"],
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "체계적으로 수집, 축적하여 다양한 용도와 방법으로 이용할 수 있게 정리한 정보의 집합체",
    correctA: "DB",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "이용자가 쉽게 DB를 구축, 유지할 수 있게 하는 관리 소프트웨어는?",
    correctA: "DBMS",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "대량의 정보를 일정한 형식에 따라 컴퓨터 등의 정보처리기기가 읽고 쓸 수 있는 DB의 특성",
    correctA: "기계 가독성",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "온라인으로 이용 가능한 DB의 특성",
    correctA: "원격 조작성",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "제품의 설계, 개발, 생산, 유통, 폐기에 이르기까지 제품의 라이프사이클 전반에 관련된 데이터를 통합하고 공유/교환할 수 있게 한 경영통합정보시스템",
    correctA: "CALS",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "학사 뿐 아니라 기타 교육행정 전 업무를 처리하는 시스템으로, 교육부 아래 각 시도별 교육청과 교육지원청들, 그리고 약 1만여 곳의 학교를 연계하는 대형 네트워크 시스템은?",
    correctA: "NEIS",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT_MULTI",
    q: "더그 래니의 3V에 추가된 4V 모두 쓰시오 (소문자 영어로)",
    correctA: ["value", "veracity", "visualization", "variability"],
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "데이터가 어떻게 사용되어 어떠한 이유로 피해자가 발생하게 되었는지 데이터 활용 로직인 알고리즘을 살펴보는 전문 인력",
    correctA: "알고리즈미스트",
    tags: ["핵심 서브노트 110제"],
    category: "1",
  },
  {
    type: "SHORT",
    q: "다음 상황에서 분석 주제는? 분석 대상이 무엇인지 알고 있음, 분석 방법을 알고 있음.",
    correctA: "최적화",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "다음 상황에서 분석 주제는? 분석 대상이 무엇인지 알고 있음, 분석 방법을 모름.",
    correctA: "솔루션",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "다음 상황에서 분석 주제는? 분석 대상이 무엇인지 모름, 분석 방법을 알고 있음.",
    correctA: "발견",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "다음 상황에서 분석 주제는? 분석 대상이 무엇인지 모름, 분석 방법을 모름.",
    correctA: "통찰",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_MULTI",
    q: "기업의 합리적 의사 결정을 방해하는 세 가지",
    correctA: ["고정 관념", "편향된 생각", "프레이밍 효과"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_MULTI",
    q: "비즈니스 모델 탐색 기법에서 5가지로 단순화한 것들",
    correctA: ["규제와 감사", "업무", "제품", "고객", "지원 인프라"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "하향식 접근법 1단계: ___ 단계",
    correctA: "문제 탐색",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "분석 기회 발굴 범위 확장할 때의 4가지 영역: ___ 관점(문제 혹은 변화가 기업에 주는 영향 탐색), ___ 확대 관점(위협이 될 상황), ___ 탐색, ___의 재해석(기업 내부를 둘러보기)",
    correctA: ["거시적", "경쟁자", "시장의 니즈", "역량"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
    weight: 2,
  },
  {
    type: "SHORT",
    q: "문제 탐색시, 분석을 적용했을 떄 업무 흐름을 개념적으로 설명한 것. 유사, 동종 업계의 탐색으로부터 정의됨",
    correctA: "분석 유스케이스",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "하향식 접근법 2단계: ___ 단계",
    correctA: "문제 정의",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "하향식 접근법 3단계: ___ 단계",
    correctA: "해결 방안 탐색",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "하향식 접근법 4단계: ___ 단계",
    correctA: "타당성 검토",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "분석 과제 발굴 - 하향식 접근법 - 타당성 검토 단계에서의 두 가지 유형: ___ 타당성, ___ 및 ___ 타당성",
    correctA: ["경제적", "데이터", "기술적"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "더블 다이아몬드, 발산과 수렴 단계를 거쳐 혁신적인 아이디어를 도출하는 방식은?",
    correctA: "디자인씽킹",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "정답이 있는 데이터로 분석 모델을 학습시키는 것",
    correctA: "지도학습",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "정답이 없는 데이터로 분석 모델을 학습시키는 것",
    correctA: "비지도학습",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "___ 접근법: 먼저 분석을 시도하고 그 결과를 확인하면서 조금씩 개선해나가는 방법",
    correctA: "프로토타이핑",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "분석 과제를 발굴한 후 작성하는 문서. 분석의 정의, 범위, 방법 등을 기술",
    correctA: "분석과제 정의서",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터 분석 방법론 차례대로 5단계(Phase)",
    correctA: [
      "분석 기획",
      "데이터 준비",
      "데이터 분석",
      "시스템 구현",
      "평가 및 전개",
    ],
    tags: ["핵심 서브노트 110제"],
    category: "2",
    weight: 2,
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터 분석 방법론 - 분석 기획에서의 태스트 3가지: 비즈니스 ___ 및 ___ 설정, 프로젝트 ___ 및 ___ 수립, 프로젝트 ___ 계획 수립",
    correctA: ["이해", "범위", "정의", "계획", "위험"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "목표 시점별 분석 기획 - ___ 중심적인 방식(빠르게 해결해야 하는 경우), ___ 방식 (지속적인 분석 내재화를 위한 경우)",
    correctA: ["과제", "마스터플랜"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터 분석 방법론 - 데이터 준비에서의 태스크: 필요한 ___ 정의, ___ 설계, 데이터 ___ 및 ___ 검정",
    correctA: ["데이터", "데이터 스토어", "수집", "정합성"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터 분석 방법론 - 데이터 분석에서의 태스크: 분석용 데이터 준비, ___ 분석, ___ 분석, ___, ___ 평가 및 검증",
    correctA: ["텍스트", "탐색적", "모델링", "모델"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터 분석 방법론 - 4단계: ___(A) 구현 에서의 태스크: 설계 및 구현, (A) ___ 및 ___ ",
    correctA: ["시스템", "테스트", "운영"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "빅데이터 분석 방법론 - 5단계: ___ 및 ___: 모델 ___, 프로젝트 평가 및 보고",
    correctA: ["평가", "전개", "발전 계획"],
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "전통적인 분석 방법론 중 ___ 분석 방법론은 데이터로부터 통계적 패전이나 지식을 찾기 위해 체계적으로 정리한 데이터 마이닝 프로세스이다.",
    correctA: "KDD",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "전통적인 분석 방법론 중 ___ 분석 방법론은 4개의 레벨과 6개의 단계로 구성되어 있다. (좀 더 세분화가 되어 있다.)",
    correctA: "CRISP-DM",
    tags: ["핵심 서브노트 110제"],
    category: "2",
  },
  {
    type: "SHORT",
    q: "프로젝트를 수행할 때 여러 개의 작은 업무 단위로 분해하고, 각각의 분해된 업무 담당자 및 수행 기간을 정의한 것은?",
    correctA: "업무분업구조",
    category: "2",
  },
  {
    type: "SHORT",
    q: "분석 방법론에서, 반복을 통해 점증적으로 개발하는 모델은 ___ 모델이다. 사용자의 요구에 초점을 맞춤",
    correctA: "프로토타입",
    category: "2",
  },
  {
    type: "SHORT",
    q: "분석 방법론에서, 반복을 통해 점증적으로 개발하는 모델은 ___ 모델이다. 사용자의 요구보다는 위험요소를 사전에 제거한다는 것에 초점을 맞춘다.",
    correctA: "나선형",
    category: "2",
  },
  {
    type: "SHORT",
    q: "모델 성능 측정 시, 모델과 실제 값 간의 차이가 적다는 척도는?",
    correctA: "정확도",
    category: "2",
  },
  {
    type: "SHORT",
    q: "모델 성능 측정 시, 반복적으로 모델을 사용했을 때 모델 값들의 편차 수준을 나타내는 것은?",
    correctA: "정밀도",
    category: "2",
  },
  {
    type: "SHORT_ORDER",
    q: "분석 마스터플랜 수립 시 분서과제의 우선 순위를 정할 때 그 기준 네 가지: ___ 중요도, ___ 성과 및 ___, 분석과제의 ___ 용이성",
    correctA: ["전략적", "비즈니스", "ROI", "실행"],
    category: "2",
    weight: 2,
  },
  {
    type: "SHORT_ORDER",
    q: "기업 분류: ___형: 낮은 준비도, 낮은 성숙도 / ___형: 낮은 준비도, 높은 성숙도 / ___형: 높은 준비도, 높은 성숙도 / ___형: 높은 준비도, 낮은 성숙도",
    correctA: ["준비", "정착", "확산", "도입"],
    category: "2",
    weight: 2,
  },
  {
    type: "SHORT",
    q: "데이터 분석 조직 유형 중 ___ 조직 구조는, 조직 내 독립적인 분석 전담 조직을 구성하고, 회사의 모든 분석 업무를 전담 조직에서 담당하는 것. 일부 협업 부서와 업무가 중복될 수 있음.",
    correctA: "집중형",
    category: "2",
  },
  {
    type: "SHORT",
    q: "데이터 분석 조직 유형 중 ___ 조직 구조는, 각 해당 업무 부서에서 직접 분석하는 형태. 전사적 관점에서 핵심 분석이 어려움.",
    correctA: "기능 중심",
    category: "2",
  },
  {
    type: "SHORT",
    q: "데이터 분석 조직 유형 중 ___ 조직 구조는, 분석 조직의 인력을 현업 부서에 배치함. 전사 차원에서 관리가 가능하고 분석 결과를 실무에 빠르게 적용 가능함",
    correctA: "분산형",
    category: "2",
  },
  {
    type: "SHORT",
    q: "데이터 웨어하우스로부터 특정 사용자가 관심을 갖는 데이터들을 주제별, 부서별로 추출하여 모은 비교적 작은 규모의 데이터 웨어하우스를 무엇이라 하는가?",
    correctA: "데이터 마트",
    category: "3",
  },
  {
    type: "SHORT",
    q: "데이터 웨어하우스로부터 특정 사용자가 관심을 갖는 데이터들을 주제별, 부서별로 추출하여 모은 비교적 작은 규모의 데이터 웨어하우스를 무엇이라 하는가?",
    correctA: "데이터 마트",
    category: "3",
  },
  {
    type: "SHORT",
    q: "데이터 ___란, 데이터 마트를 개발한 후 데이터를 정제하고 분석 변수를 처리하는 과정이다. 빅데이터 분석 단계에 들어가기 전 필요하다. ",
    correctA: "전처리",
    category: "3",
  },
  {
    type: "SHORT",
    q: "데이터로부터 기본적인 통계 자료를 추출한 변수는?",
    correctA: "요약변수",
    category: "3",
  },
  {
    type: "SHORT",
    q: "범용으로 활용되는 기본적인 통계자료가 아닌, 특정한 목적을 갖고 조건을 만족하는 변수들을 새롭게 생성한 것",
    correctA: "파생변수",
    category: "3",
  },
  {
    type: "SHORT",
    q: "존재하지 않는 데이터",
    correctA: "결측값",
    category: "3",
  },
  {
    type: "SHORT",
    q: "결측값이 존재하는 데이터를 삭제하는 방법 중 결측값을 단순히 삭제하는 방법은?",
    correctA: "단순 대치법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "결측값이 존재하는 데이터를 삭제하는 방법 중 평균 혹은 중앙값으로 결측값을 대치하여 불완전한 자료를 완전한 자료로 만드는 방법은?",
    correctA: "평균 대치법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "다른 데이터와 달리 극단적으로 크거나 작은 값을 의미하는 것은?",
    correctA: "이상값",
    category: "3",
  },
  {
    type: "SHORT",
    q: "평균으로부터 표준편차 3 만큼 떨어진 값들을 이상값으로 인식하는 방법은?",
    correctA: "ESD",
    category: "3",
  },
  {
    type: "SHORT",
    q: "모집단의 원소에 차례대로 번호 부여한 후 일정한 간격을 두고 데이터를 추출하는 방법",
    correctA: "계통 추출법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "여러 그룹으로 나눈 것 중 랜덤으로 선택하는 방법. 단, 그룹 간엔 동질적이며 그룹 내 데이터는 서로 이질적이다.",
    correctA: "집락 추출법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "여러 그룹으로 나눈 것 중 랜덤으로 선택하는 방법. 단, 그룹 간엔 이질적이며 그룹 내 데이터는 서로 동질적이다.",
    correctA: "층화 추출법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "측정 대상이 어느 집단에 속하는지 나타내는 자료",
    correctA: "명목척도",
    category: "3",
  },
  {
    type: "SHORT",
    q: "측정 대상이 명목척도이면서 순서가 있는 자료",
    correctA: "서열척도",
    category: "3",
  },
  {
    type: "SHORT",
    q: "양을 측정할 수 있으며, 두 구간 사이에 의미가 있는 자료",
    correctA: "구간척도",
    category: "3",
  },
  {
    type: "SHORT",
    q: "측정 대상이 구간척도이면서 절대적 기준 0이 존재하여 사칙연산이 가능한 자료",
    correctA: "비율척도",
    category: "3",
  },
  {
    type: "SHORT",
    q: "표본에서 얻은 통계치를 바탕으로 모수를 추정하는 통계 기법",
    correctA: "추리통계",
    category: "3",
  },
  {
    type: "SHORT",
    q: "표본에서 얻은 통계치를 바탕으로 모수를 추정하는 통계 기법",
    correctA: "추리통계",
    category: "3",
  },
  {
    type: "SHORT",
    q: "교집합이 없는 사건",
    correctA: "배반사건",
    category: "3",
  },
  {
    type: "SHORT",
    q: "서로 영향을 주지 않는 두 개의 사건은 서로 ___ 이다.",
    correctA: "독립",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 분포: 성공/실패로 나뉘어지는 시행에서, 성공 확률이 p인 분포",
    correctA: "베르누이",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 분포: 성공/실패로 나뉘어지는 n번의 베르누이 시행에서, 성공 확률이 p일 때, k번 성공할 확률의 분포",
    correctA: "이항",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 분포: 성공 확률이 p인 베르누이 시행에서 처음으로 성공이 나올 때까지 k번 실패학 확률의 분포",
    correctA: "기하",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 분포: n번의 베르누이 시행에서 각 시행이 3개 이상의 결과를 가질 수 있는 확률의 분포",
    correctA: "다항",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 분포: 단위시간 혹은 단위공간 내에서 발생할 수 있는 사건의 발생 횟수에 대한 확률 분포",
    correctA: "포아송",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 분포: 단위시간 혹은 단위공간 내에서 발생할 수 있는 사건의 발생 횟수에 대한 확률 분포",
    correctA: "포아송",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 분포: 연속형에서 모든 값에 대하여 같은 확률을 갖고 있는 분포",
    correctA: "균일",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___분포: 평균이 μ이고, 표준편차가 𝜎인 분포",
    correctA: "정규",
    category: "3",
  },
  {
    type: "SHORT",
    q: "표준정규분포를 따르는 확률변수 Z_1, Z_2, ..., Z_n의 제곱 합 X 는 자유도가 n인 ___ 분포를 따른다.",
    correctA: "카이제곱",
    category: "3",
  },
  {
    type: "SHORT",
    q: "서로 독립인 두 카이제곱 분포를 따르는 확률변수 V_1 ~ X^2(k_1), V_2 ~ X^2(k_2)를 각각의 자유도로 나누었을 때 서로의 비율 X 는 자유도가 k_1, k_2인 ___ 분포를 따른다.",
    correctA: "F",
    category: "3",
  },
  {
    type: "SHORT",
    q: "귀무가설(H_0)이 사실인데 틀렸다고 결정(기각)하는 오류",
    correctA: "제1종 오류",
    category: "3",
  },
  {
    type: "SHORT",
    q: "귀무가설(H_0)이 거짓인데 옳다고 결정(채택)하는 오류",
    correctA: "제2종 오류",
    category: "3",
  },
  {
    type: "SHORT",
    q: "실험과 연구를 통해 기각하고자 하는 가설. 이것의 기각을 통해 입증하고자 하는 주장을 관철할 수 있음.",
    correctA: "귀무가설",
    category: "3",
  },
  {
    type: "SHORT",
    q: "귀무가설이 틀렸다고 판단될 경우 채택될 가설",
    correctA: "대립가설",
    category: "3",
  },
  {
    type: "SHORT",
    q: "귀무가설을 판단하기 위해서, 표본조사를 실시하였을 떄 특정 수식에 의하여 포본들로부터 얻을 수 있는 값",
    correctA: "검정통계량",
    category: "3",
  },
  {
    type: "SHORT",
    q: "모수가 특정한 구간 안에 존재할 것이라 예상하는 것",
    correctA: "구간추정",
    category: "3",
  },
  {
    type: "SHORT",
    q: "모수를 추정할 때 하나의 특정한 값이라 추정하는 것",
    correctA: "점추정",
    category: "3",
  },
  {
    type: "SHORT",
    q: "어느 한 쪽으로 편향되지 않아서 모수를 추정하기에 이상적인 값",
    correctA: "불편추정량",
    category: "3",
  },
  {
    type: "SHORT",
    q: "확률분포의 뾰족한 정도",
    correctA: "첨도",
    category: "3",
  },
  {
    type: "SHORT_ORDER",
    q: "___(A)는 확률 분포의 비대칭 정도를 나타내는 척도이며, A가 0보다 __면 최빈값 < 중앙값 < 평균이다.",
    correctA: ["왜도", "크다"],
    category: "3",
  },
  {
    type: "SHORT",
    q: "어떤 확률변수가 취할 수 있는 값의 평균 값",
    correctA: "기댓값",
    category: "3",
  },
  {
    type: "SHORT",
    q: "데이터들이 중심에서 얼마나 떨어져 있는지를 알아보기 위한 측도",
    correctA: "분산",
    category: "3",
  },
  {
    type: "SHORT",
    q: "귀무가설이 참인데도 이를 잘못 기각하는 오류를 범할 확률의 최대 허용 한계",
    correctA: "유의수준",
    category: "3",
  },
  {
    type: "SHORT",
    q: "귀무가설을 지지하는 정도. 대립가설이 우연히 나올 확률.",
    correctA: "유의확률",
    category: "3",
  },
  {
    type: "SHORT",
    q: "세 개 이상의 모집단이 있을 때 여러 집단 사이의 평균을 비교하는 검정 방법",
    correctA: "분산분석",
    category: "3",
  },
  {
    type: "SHORT_MULTI",
    q: "분산분석을 위한 세 가지 조건은?",
    correctA: ["정규성", "등분산성", "독립성"],
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 검정: 실험 결과 얻어진 관측값이 예상값과 일치하는지 여부를 검정하는 방법이다.",
    correctA: "적합도",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 검정: 모집단이 두 개의 변수에 의해 범주화됐을 때 그 두 변수들 사이의 관계가 독립적인지 아닌지 검정하는 것",
    correctA: "독립성",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 검정: 관측값들이 정해진 범주 내에서 서로 비슷하게 나타나고 있는지를 검정하는 것",
    correctA: "동질성",
    category: "3",
  },
  {
    type: "SHORT",
    q: "모집단의 분포와 상관없이 표본의 개수가 커질 수록 표본평균의 분포는 정규분포에 가까워지는 현상",
    correctA: "중심극한정리",
    category: "3",
  },
  {
    type: "SHORT",
    q: "두 변수 간의 선형적 관계가 존재하는지 알아보는 분석 방법",
    correctA: "상관분석",
    category: "3",
  },
  {
    type: "SHORT",
    q: "상관분석에서 측정된 두 변수가 등간척도 혹은 비율척도일 때 사용하는 것은?",
    correctA: "피어슨 상관계수",
    category: "3",
  },
  {
    type: "SHORT",
    q: "상관분석에서 측정된 두 변수가 서열척도일 때 사용하는 것은?",
    correctA: "스피어만 상관계수",
    category: "3",
  },
  {
    type: "SHORT",
    q: "상관분석의 귀무가설은 '두 변수 간에 상관관계가 ___' 이다.",
    correctA: "없다",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___이란, 하나 이상의 독립변수들이 종속변수에 얼마나 영향을 미치는지 추정하는 통계기법이다.",
    correctA: "회귀분석",
    category: "3",
  },
  {
    type: "SHORT_MULTI",
    q: "회귀분석의 가정 다섯 가지",
    correctA: ["선형성", "독립성", "등분산성", "정규성", "비상관성"],
    category: "3",
  },
  {
    type: "SHORT",
    q: "___이란, 실제 관측치와 추세선에 의해 예측된 점 사이의 거리, 즉 오차를 제곱해 더한 값을 최소화하는 것.",
    correctA: "최소제곱법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "회귀모형의 통계적 유의성은 ___ 를 통해 확인한다.",
    correctA: "F 검정",
    category: "3",
  },
  {
    type: "SHORT",
    q: "회귀모형의 ___ 이 좋다는 말은 데이터들의 분포가 회귀선에 밀접하게 분포하고 있다는 의미이다.",
    correctA: "설명력",
    category: "3",
  },
  {
    type: "SHORT",
    q: "표본집단에 의한 회귀식과 관측값 사이에 나타나는 차이",
    correctA: "잔차",
    category: "3",
  },
  {
    type: "SHORT",
    q: "모집단에 의한 회귀식과 관측값 사이에 나타나는 차이",
    correctA: "오차",
    category: "3",
  },
  {
    type: "SHORT",
    q: "독립변수 간 강한 상관관계가 나타나는 문제",
    correctA: "다중공선성",
    category: "3",
  },
  {
    type: "SHORT_ORDER",
    q: "___ 값을 구해서 이게 ___ 를 넘는다면 보통 다중공선성이 있다고 판단할 수 있다.",
    correctA: ["분산팽창요인", "10"],
    category: "3",
  },
  {
    type: "SHORT",
    q: "독립변수 간 강한 상관관계가 나타나는 문제",
    correctA: "다중공선성",
    category: "3",
  },
  {
    type: "SHORT",
    q: "회귀모형의 성능지표로서, MSE에 변수 수 만큼 페널티를 주는 지표는?",
    correctA: "AIC",
    category: "3",
  },
  {
    type: "SHORT",
    q: "회귀모형의 성능지표로서, AIC의 단점인, 표본이 커질 때 부정확하다는 단점을 보완한 지표는?",
    correctA: "BIC",
    category: "3",
  },
  {
    type: "SHORT",
    q: "최소자승법으로 사용하여 추정된 회귀모형의 적합성을 평가하는 데 사용된다.",
    correctA: "멜로우 Cp",
    category: "3",
  },
  {
    type: "SHORT",
    q: "회귀분석 시 변수 선택에 있어 기준 통계치에 가장 영향을 많이 줄 것으로 판단되는 변수부터 하나씩 추가하면서 모형을 선택하는 것",
    correctA: "전진선택법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "회귀분석 시 변수 선택에 있어 가장 영향을 적게 주는 것부터 하나씩 제거하면서 모형을 선택하는 것",
    correctA: "후진제거법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "변수를 추가하면서 추가될 때 예상되는 벌점 값과 이미 추가된 변수가 제거될 때 예상되는 벌점 값이 가장 작도록 만들어나가는 방법",
    correctA: "단계별 방법",
    category: "3",
  },
  {
    type: "SHORT",
    q: "모델이 학습 데이터를 과하게 학습하는 것",
    correctA: "과적합",
    category: "3",
  },
  {
    type: "SHORT",
    q: "모델이 너무 단순하여 학습 데이터조차 제대로 예측하지 못하는 경우",
    correctA: "과소적합",
    category: "3",
  },
  {
    type: "SHORT_ORDER",
    q: "회귀분석에서 과적합되면 계수의 크기도 ___ 하게 된다. 따라서 이를 방지하기 위해 ___ 를 사용한다.",
    correctA: ["과도", "정규화 선형회귀"],
    category: "3",
  },
  {
    type: "SHORT",
    q: "가중치들의 절댓값의 합을 최소화하는 것을 제약조건으로 추가하는 방법",
    correctA: "라쏘",
    category: "3",
  },
  {
    type: "SHORT",
    q: "가중치들의 제곱의 합을 최소화하는 것을 제약조건으로 추가하는 방법",
    correctA: "릿지",
    category: "3",
  },
  {
    type: "SHORT",
    q: "가중치들의 절댓값의 합과 제곱의 합을 최소화하는 것을 제약조건으로 추가하는 방법",
    correctA: "엘라스틱넷",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 회귀는 종속변수가 범주형 변수(사망/생존, 0/1)인 경우에 사용한다.",
    correctA: "로지스틱",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 회귀는 종속변수가 특정 시간 동안 발생한 사건의 건수에 대한 도수 자료인 경우면서, 정규분포를 따르지 않거나 등분산성을 만족하지 못하는 경우 사용된다.",
    correctA: "포아송",
    category: "3",
  },
  {
    type: "SHORT",
    q: "회귀분석에 있어 자기상관성이 존재하는지 검정하는 방법",
    correctA: "더빈 왓슨 검정",
    category: "3",
  },
  {
    type: "SHORT",
    q: "다차원 척도법에서는 개체의 실제 거리와 모형에 의해 추정된 거리 사이의 적합도를 측정하기 위해 ___ 척도를 사용한다.",
    correctA: "stress",
    category: "3",
  },
  {
    type: "SHORT_ORDER",
    q: "___ 이란, 여러 개의 변수 중 서로 상관성이 높은 변수들의 ___으로 새로운 변수를 만ㄷ르어 기존 변수를 요약 및 축소하는 분석 방법이다.",
    correctA: ["주성분분석", "선형결합"],
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 은, x축을 성분의 개수, y축을 고윳값으로 하는 그래프로 주성분의 개수를 선택하는 데 도움을 준다.",
    correctA: "scree plot",
    category: "3",
  },
  {
    type: "SHORT",
    q: "___ 이란 두 개의 확률 변수의 선형관계를 나타낸다. 하나의 확률 번슈의 증감에 따른 다른 확률 변수의 증감 경향에 대한 측도이다. 대부분의 시계열 자료들은 이것이 0이 아니다.",
    correctA: "공분산",
    category: "3",
  },
  {
    type: "SHORT_MULTI",
    q: "시계열 자료의 정상성 조건 중 평균은 ___ 해야 한다. 만약 그렇지 않다면 ___을 통해 정상화할 수 있다.",
    correctA: ["일정", "차분"],
    category: "3",
  },
];
