# name: Deploy DB Migrations

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-22.04

#     env:
#       SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
#       SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
#       SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

#     steps:
#       - uses: actions/checkout@v3

#       - uses: supabase/setup-cli@v1
#         with:
#           version: 1.27.10

#       - run: |
#           supabase link --project-ref $SUPABASE_PROJECT_ID --password $SUPABASE_DB_PASSWORD
#           supabase db push
