name: Prisma Deploy
on:
  push:
    branches:
      - main

jobs:
  prisma-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.4

      - name: Install dependencies
        run: pnpm install

      - run: pnpm build

      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_DATABASE_URL: ${{ secrets.DIRECT_DATABASE_URL }}
